-- Create the checkins table
CREATE TABLE checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client_profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    water_intake_level TEXT CHECK (water_intake_level IN ('low', 'medium', 'high')),
    weight NUMERIC,
    calories INTEGER,
    protein INTEGER,
    carbs INTEGER,
    fats INTEGER,
    steps INTEGER,
    stress_level INTEGER CHECK (stress_level BETWEEN 1 AND 10),
    sleeping_hours NUMERIC,
    service_rating INTEGER CHECK (service_rating BETWEEN 1 AND 10)
);

-- Add comments for clarity
COMMENT ON TABLE checkins IS 'Daily check-ins for clients';
COMMENT ON COLUMN checkins.sleeping_hours IS 'Number of hours sleep obtained the previous night';
