-- Create notifications table if it doesn't exist
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- or just text/string if not using Auth strictly yet
  type text not null,
  message text not null,
  related_id bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  read boolean default false
);

-- Enable Realtime for the table
alter publication supabase_realtime add table notifications;
